name: Package Addon
permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create zip
        run: zip -r state_machines.zip addons/state_machines

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: state_machines.zip
